### ISSUE TITLE
Version command reads version information from GUI app, not CLI tool

### ISSUE THREAD

**Issue by nider** [ninxsoft/mist-cli#104] opened 2022-09-26 01:24 UTC
When running `mist version` the tool appears to be reading version information from the GUI app rather than the CLI tool, resulting in this output:

```shell
% mist version       
1.8 (Latest: 0.2)
```

**Comment by ninxsoft** [comment] 2022-09-26 05:06
Hi @nider, this is a duplicate of https://github.com/ninxsoft/mist-cli/issues/92, which was fixed in https://github.com/ninxsoft/mist-cli/commit/78b95a08ebf794fb1d2a2ba35a6b4eb8f5cf0022.

A new version reflecting this change will be released today!

**Closed by ninxsoft** 2022-09-26 05:06 UTC
Labels: bug, duplicate
